version: "3.9"

services:
 frontend:
    container_name: frontend
    ports:
      - "8001:80" 

    restart: always
    networks:
      - internal_net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M